Title: Esoteric Physics I - The Hall Effect
Date: 2010-05-23 23:31:00
Tags: magnetism, hall effect, current, esoteric
Category: old
Slug: esoteric-physics-i-the-hall-effect
Author: Jesse


What we usually do here at the The Virtuosi is take an interesting problem, and work out the physical principles behind what we're seeing.  Or pose a question and try to answer it.  Now, I'm a big fan of this kind of thing, which is why I've done so much of it.  But I worry that it might give a slightly skewed view of physics.  Sure, physics explains things.  That's why we do it.  But not everything in physics is <a href="http://thevirtuosi.blogspot.com/2010/04/laser-gun-recoil-follow-up.html">laser guns</a> and <a href="http://thevirtuosi.blogspot.com/2010/05/solar-sails-i.html">solar sails</a>.  There are a lot of interesting physics phenomena that the general public will never hear about, because they're just too, well, esoteric.  What I'm going to do is occasionally talk about such effects, and, for some of them, give you applications for these strange effects you might see on a day-to-day basis.  Today I'm going to examine the Hall effect.

<a name='more'></a>The Hall effect is simple, as these things go, once we understand the pieces.  The first piece is that magnetic fields deflect moving electrically charged particles.  I don't think I can give you a good simple reason for this, you're just going to have to trust me (for those interested, I'd argue that the relativistic transformation of a magnetic field is an electric field, and that will certainly deflect an electrically charged particle).  This is a piece of the Lorentz force.  The next piece that we need to know is that opposite electrically charged particles attract.  So a positively charged particle attracts a negatively charged particle.  Knowing those two things we can detail the Hall effect.
<div class="separator" style="clear: both; text-align: center;"><a href="http://4.bp.blogspot.com/_SYZpxZOlcb0/S_nxJSw3bQI/AAAAAAAAABU/Mi2_jDtskus/s1600/Hall+effect+pos.JPG" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" src="http://4.bp.blogspot.com/_SYZpxZOlcb0/S_nxJSw3bQI/AAAAAAAAABU/Mi2_jDtskus/s320/Hall+effect+pos.JPG" /></a></div>Take the slab pictured above.  We run an electric current through it.  Conventionally we take current as moving positively charged particles.  There is a magnetic field into the screen.  This deflects the positive charges up the screen, as shown, with some upward force.  Over some time, we will accumulate positive charges at the top.  Because there is no net charge in our slab, this must leave a region of negative charge at the bottom.  These regions of charge will attract, and cancel out the force from the magnetic field.  This charge separation results in a voltage differential between the two sides of the slab, which is what we actually measure.

The Hall effect has some nifty consequences physically.  I mentioned that conventionally we take current to be positive particles moving.  A microscopic picture of our conductors will tell us that, in general, electrons are what we consider to be flowing in an electric current.  Now, it turns out that our magnetic field will deflect electrons moving opposite our current direction (negative current moving backwards is the same as positive current moving forwards) to the same side as our hypothetical positive particles got deflected to.  This generates a charge differential with negative and positive charges on the opposite sides of the slab (shown below), which means the voltage is negative what we would have measured above!  This means we expect to get a certain sign of the measured Hall voltage, which we can predict.  This sign would correspond to negative particles (electrons) being the moving charge carriers in substances.  It turns out that there are some substances (some semiconductors) where the sign of the Hall voltage is opposite what we expect from electrons.  This means that in those substances the current is being carried by positive particles!  I won't explain what that means here (I may address that in a later post), but I hope you can see why that would be fascinating.  We expected to have electrons moving, and it turns out that something else is really doing the moving.  The Hall effect is an experimental result that helped suggest a whole new way of thinking about conduction in materials.
<div class="separator" style="clear: both; text-align: center;"><a href="http://2.bp.blogspot.com/_SYZpxZOlcb0/S_nxRTxhhoI/AAAAAAAAABc/AJGpkjd-iWU/s1600/Hall+effect+neg.JPG" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" src="http://2.bp.blogspot.com/_SYZpxZOlcb0/S_nxRTxhhoI/AAAAAAAAABc/AJGpkjd-iWU/s320/Hall+effect+neg.JPG" /></a></div>Beyond being very interesting physics, there are some applications to this effect.  It is an easy way to create a magnetic field sensor.  Take a slab of material, run a current through it, and measure the voltage on the sides.  Where do we use magnetic field sensors?  Well, they sometimes show up as a way to tell if something is open or closed.  Put a magnet in your lid, and a Hall effect sensor in the lip the lid rests on.  When it is closed, you'll measure a voltage, and when it is open you won't.  Now you can tell if it is open or closed.  A little imagination, and you can see how this would be useful for all kinds of switches.  Hit the switch, move your magnet, and change your voltage.  According to Wikipedia, Hall effect switches are used in things as diverse as paintball guns and go-cart speed controls.  They could also be used as a speed or acceleration measurement in a rotating system.  Attach a magnet to the rotating object, put a sensor at a fixed location, and measure how the voltage in your sensor changes as the object sweeps past it.  There are many more applications, but this is just to give you a taste of how this seemingly esoteric physics concept may show up in your everyday life.  It's not just the interesting problems we often work on this blog, physics is everywhere.  In many different guises
